"""
BONGAS-ML: Sovereign Blackbox Compiler

This script compiles the `sovereign/trainer.py` and `sovereign/models.py` 
modules into a C-extension (.so). 

This is the exact mechanism used to protect our IP (Intellectual Property). 
By shipping the compiled `trainer.so` to the client's infrastructure, 
they can train models on their private data without ever seeing the proprietary 
PyTorch training loops, loss functions, or data joining logic.
"""

import os
import shutil
from pathlib import Path
from setuptools import setup
from Cython.Build import cythonize
from Cython.Compiler import Options

# Optimize C generation for production
Options.docstrings = False
Options.annotate = False

def build_sovereign_trainer():
    print("=== BONGAS-ML Sovereign Compiler ===")
    
    # 1. Compile the Python files to C-extensions
    setup(
        name='Bongas Sovereign Trainer',
        ext_modules=cythonize(
            ["factory/trainer/trainer.py", "factory/trainer/models.py"],
            compiler_directives={
                'language_level': "3", 
                'boundscheck': False,
                'wraparound': False,
                'initializedcheck': False,
            },
            quiet=True
        ),
        script_args=["build_ext", "--inplace"]
    )
    
    # 2. Package the output for the client release
    release_dir = Path("../bongas-ai/release/trainer")
    release_dir.mkdir(parents=True, exist_ok=True)
    
    # Move the generated .so files (e.g., trainer.cpython-310-x86_64-linux-gnu.so)
    # and rename them cleanly to `trainer.so` and `models.so`
    for so_file in Path("bongas_ml/sovereign").glob("*.so"):
        clean_name = so_file.name.split('.')[0] + ".so"
        target_path = release_dir / clean_name
        shutil.move(str(so_file), str(target_path))
        print(f"Secured and Packaged: {target_path}")

    # Cleanup C files generated by Cython
    for c_file in Path("bongas_ml/sovereign").glob("*.c"):
        c_file.unlink()
        
    print("=== Compilation Complete: Ready for On-Premise Deployment ===")

if __name__ == "__main__":
    build_sovereign_trainer()